cluster_name: ray-cluster

initial_workers: 2
min_workers: 2
max_workers: 2

provider:
    type: aws
    region: us-east-1
    availability_zone: us-east-1a,us-east-1b,us-east-1c
    security_group:
        GroupName: ray_client_security_group
        IpPermissions:
              - FromPort: 22
                ToPort: 22
                IpProtocol: TCP
                IpRanges:
                    - CidrIp: 72.21.199.80/28
                    - CidrIp: 52.46.250.0/23
                    - CidrIp: 72.21.196.64/29
                    - CidrIp: 72.21.217.0/24
                    - CidrIp: 72.21.198.64/29
                    - CidrIp: 54.240.217.0/27
                    - CidrIp: 54.239.112.0/24
                    - CidrIp: 15.221.4.0/23
                    - CidrIp: 54.239.98.0/24
                    - CidrIp: 52.94.133.128/25
              - FromPort: 10001
                ToPort: 10001
                IpProtocol: TCP
                IpRanges:
                    - CidrIp: 72.21.199.80/28
                    - CidrIp: 52.46.250.0/23
                    - CidrIp: 72.21.196.64/29
                    - CidrIp: 72.21.217.0/24
                    - CidrIp: 72.21.198.64/29
                    - CidrIp: 54.240.217.0/27
                    - CidrIp: 54.239.112.0/24
                    - CidrIp: 15.221.4.0/23
                    - CidrIp: 54.239.98.0/24
                    - CidrIp: 52.94.133.128/25
    cache_stopped_nodes: False

available_node_types:
  ray.head.default:
    node_config:
      InstanceType: r5n.2xlarge
      IamInstanceProfile:
        Arn: arn:aws:iam::336392948345:instance-profile/ray-cluster-instance-profile
      ImageId: ami-0ea510fcb67686b48

  ray.worker.default:
      min_workers: 2
      max_workers: 2
      node_config:
        InstanceType: r5n.2xlarge
        IamInstanceProfile:
          Arn: arn:aws:iam::336392948345:instance-profile/ray-cluster-instance-profile
        ImageId: ami-0ea510fcb67686b48

setup_commands:
- pip install git+https://github.com/awslabs/aws-data-wrangler.git@wrangler-3.0.0
- pip install ray[default,data]
- pip install modin
